### ISSUE TITLE
OPSEC Offensive Notion

### ISSUE THREAD

**Issue by soazt** [mttaggart/OffensiveNotion#131]
Hi. Congratulations on your project, simply spectacular.

The agent (.exe) that is built and communicates with the notion API (C&C) can be considered **malware**? Understanding that malware is any kind of software with malicious intent.

Could you expand your point of view on why **virustotal[.]com** does not detect it as malicious and evades most of the cybersecurity controls (XDR, Proxy, NAC)?

**Comment by mttaggart** [comment]
This is not malware. It is an educational research project that can be used in authorized offensive security engagements. Like any such tool, it is possible for it to be abused, which is why we provide signatures and detection rules for defenders.

Last I checked, VT does in fact detect the agent as malicious. We even have our own Windows Defender signature!

However, when you compile the agent, you do so with a unique encryption key for strings. Some tools use simplistic signatures that will fail to detect the rest of the agent's signatures without unencrypted strings.

NAC has nothing to do with this layer and does not apply as a control against this software. As for HTTP proxies, you'd have to check whatever detection rules are in place.

As far as EDR, keep in mind it isn't just about launching the agent, but interacting with it. I think you'll find that naive tradecraft like process injection will be detected quite easily.
