### ISSUE TITLE
[New Feature] macOS agent 👀

### ISSUE THREAD

**Issue by HuskyHacks** [mttaggart/OffensiveNotion#54]

**Comment by mttaggart** [comment]
Getting close. Leaving this here as a note about code signing. This should likely be included in a sub-page on the Wiki about deployment on macOS: https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html

**Comment by HuskyHacks** [comment]
Mahaps there exists a tool like Limelighter but for macOS?

https://github.com/Tylous/Limelighter

**Comment by mttaggart** [comment]
Unbelievably, this works now.

The macOS build has full feature parity with the Linux build.

Persistence is accomplished one of two ways:

1. `loginitem`: Use AppleScript to create a loginitem
2. `launchagent`: Create a LaunchAgent `plist` either in the user folder or in `/Library/System` if elevated.

Although the build will not run without security overrides, that's an issue of code signing which can be fixed with a legit developer account.

Completed as of d527eeef6897f4197565468eabe6c284e84adc5d

**Comment by HuskyHacks** [comment]
that is HUGE
