### ISSUE TITLE
[New Feature] `execute-assembly`

### ISSUE THREAD

**Issue by HuskyHacks** [mttaggart/OffensiveNotion#56]
- Loads CLR into app
- Downloads assembly remotely
- Load/execute assembly and return results
- Unload appdomain

Currently looking for help on this one, need a good example of Rust implementation of loading the CLR and FFI for .NET in general

**Comment by yamakadi** [comment]
I managed to get some things to execute, but it's really fiddly and existing mscoree-sys crates don't always work. I'll check if the code survived — I do recall destroying everything in a fit of rage.

One sidenote, I actually tried just doing the execute-assembly part in Nim and passing the necessary variables and data to it using Rust FFI. NimMain is a deal breaker though — it destroys the pointers passed back to Rust and somehow breaks consequent calls to the same FFI function. `--gc:arc` wasn't helpful, since you can't use sequences with it :(

**Comment by yamakadi** [comment]
Finally got CLR working 😁 

→ [yamakadi/clroxide](https://github.com/yamakadi/clroxide)

**Comment by mttaggart** [comment]
This is so exciting, @yamakadi! We'll be delving into incorporating this into ON as soon as possible. Great work!

**Comment by mttaggart** [comment]
Added in [4fa2c01](https://github.com/mttaggart/OffensiveNotion/pull/137/commits/4fa2c01afc4c635e4d6609285fdbdcd464a0e271)
